[package]
name = "kusatsu-entity"
version = "0.1.0"
edition = "2021"
description = "Database entities for Kusatsu file sharing"

[dependencies]
sea-orm = { workspace = true }
serde = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }